# Generated by Django 4.1.3 on 2024-04-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compressor", "0002_remove_compressedimage_algorithm_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compressedimage",
            old_name="huffman_guide",
            new_name="huffman_codes",
        ),
        migrations.AddField(
            model_name="compressedimage",
            name="size_reduction",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
