# Generated by Django 4.1.3 on 2024-04-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "compressor",
            "0003_rename_huffman_guide_compressedimage_huffman_codes_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compressedimage",
            name="file_loc",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
